### PR TITLE
🚑Hotfix/hotjar init error

### PR DESCRIPTION
**Pull request by bdolly**
## Motivation 
The hotjar script loading was throwing an error in the console and preventing any of the hotjars analytics tracking features from being enabled. We want to fix this so that we can start recording user sessions and enable the feedback widget. 

## Implementation details 
Moves the script loading from the analyticsTracking service into the document head using the standard [hotjars script tag](https://help.hotjar.com/hc/en-us/articles/115009336727-How-to-Install-your-Hotjar-Tracking-Code)
deprecates the need for the `REACT_APP_HOTJAR_HOST`

### CODE REVIEW

**Comment by jberube** [comment]
That would be related to https://github.com/kids-first/kf-portal-ui/issues/1620 right?

**Comment by bdolly** [comment]
> Could the script that load the hj script be at the end of the body rather than in the head?

It could be at the end but it's set to load `async` so it's non-blocking in the head

**Comment by bdolly** [comment]
> That would be related to #1620 right?

Yup this addresses that issue and would allow us to add the Hotjar feedback widget to the portal

**Comment by jberube** [comment]
Ok, LGTM, I'll wait until after we push the "white page" hotfix to production before merging, though, since we have no more time to test and Vincent has a demo coming.

**Comment by jberube** [comment]
Just realized that this PR points to `master` when it should be pointing to `next`.

I'll try to fix it real quick.

**Comment by bdolly** [comment]
@jberube change based to `next`, would you mind checking out the conflict with `src/components/CohortBuilder/DeleteVirtualStudiesModalContent.js` as I'm not familiar with that file

**Comment by jberube** [comment]
Closed. Has been replaced by #1669 .

**Pull request closed without merging**
