### PR TITLE
update stats queries

### PR DESCRIPTION
**Pull request by Jephuff**
not sure how many participants there should be, but now it's 100
image

### CODE REVIEW

**Comment by andricDu** [comment]
Still not correct.

**Comment by andricDu** [comment]
@Jephuff the aggs being generated by the middleware seem to default to a size:100

**Comment by Jephuff** [comment]
that explains the 100 :) 
that will be a fix in arranger. I'll take a look.

**Comment by andricDu** [comment]
I'm guessing the number in the UI is just a count of the returned buckets which totally makes sense as its the sum of unique terms.

**Comment by Jephuff** [comment]
I think this is what we really want https://www.elastic.co/guide/en/elasticsearch/guide/current/cardinality.html
I don't know if there is a good way of getting all buckets. I'll update with a bad way for now and look more into that.

**Comment by andricDu** [comment]
Issue with cardinality is that it is not an exact count. We went down that road in ICGC and decided it wasn't good as the numbers in the UI were not accurate. I'll double check to see what we did there just so we can have another reference.

**Comment by andricDu** [comment]
Yea it looks like even in ICGC to produce the summary data we counted the number of buckets https://github.com/icgc-dcc/dcc-portal/blob/develop/dcc-portal-server/src/main/java/org/icgc/dcc/portal/server/repository/FileRepository.java#L753

And we currently use a large constant for that https://github.com/icgc-dcc/dcc-portal/blob/develop/dcc-portal-server/src/main/java/org/icgc/dcc/portal/server/repository/FileRepository.java#L161

**Comment by andricDu** [comment]
@Jephuff u da mvp
image

**Pull request merged**
