### PR TITLE
📈 adds immediate dom content to user snap

### PR DESCRIPTION
**Pull request by hlminh2000**
Putting on my mad scientist hat to do an extreme log measure :P

Can't reproduce the google button issue, so adding this for when the issue is reported again so we can see what is and isn't actually in the dom

### CODE REVIEW

**Comment by hlminh2000** [comment]
@bdolly would be great to get your thoughts on this. I think it'll be useful in situations like the google button issue, but maybe it's too extreme? lmk

**Comment by bdolly** [comment]
@hlminh2000 so this just adds the initial rendered DOM as a string to the usersnap meta?

**Comment by hlminh2000** [comment]
It should be adding it just before sending the data no?

**Comment by bdolly** [comment]
@hlminh2000 yeah, I think that's how it should work. I think it should be good to roll out and see how it does.

**Pull request merged**
