### PR TITLE
Remove the Phenotypes Template card

### PR DESCRIPTION
**Pull request by jaouad-benassila**

### CODE REVIEW

**Comment by jaouad-benassila** [comment]
I don't know if there is need for this card in the future or not ?

**Comment by ciaranschutte** [comment]
@jaouad-benassila We just need to make the cards remaining take up the whole width of the container by removing the extra dom el and increasing the Col xs space

**Comment by jaouad-benassila** [comment]
remove

**Comment by hlminh2000** [comment]
haha @kcullion I feel like we might want to make the cards taller with all the new real estate eh :)

**Comment by kcullion** [comment]
@hlminh2000 hmmm - I would say just a bit taller so you can see the full "p" of the word Participants on the x-axis. Let's see how that looks first.
screen shot 2019-03-06 at 9 28 41 am

**Pull request merged**
