### PR TITLE
Bug fix for svg data not being uri encoded. (non-chrome browsers)

### PR DESCRIPTION
**Pull request by andricDu**
Not sure if there is a better place to ensure the encoding.

### CODE REVIEW

**Comment by alex-wilmer** [comment]
I think the best solution is to use the svg directly and not using an img tag. jonE did this here https://github.com/kids-first/kf-portal-ui/blob/master/src/icons/CircleCheckIcon.js

**Comment by andricDu** [comment]
Works for me.

**Comment by andricDu** [comment]
Updated to using svg elements rather than img elements per @alex-wilmer 's suggestion

**Comment by cy** [comment]
so the reason I wrapped the svgs in img tags was it seemed to respect the width/height better, look at the /join page ;(
image

**Comment by andricDu** [comment]
Thanks @cy I'll do that.

**Pull request merged**
