### PR TITLE
Adds usersnap integration

### PR DESCRIPTION
**Pull request by bdolly**
Adds [UserSnap](https://usersnap.com/) feedback widget to all pages for anonymous and authenticated users.

### CODE REVIEW

**Comment by hlminh2000** [comment]
:P thanks @jgnieuwhof I was wondering bout the modal styling too

**Comment by bdolly** [comment]
@jgnieuwhof working on preview. Looks good to merge to me, if you're cool with it

**Comment by bdolly** [comment]
scratch that looks like something got borked on the FileRepo sidebar

**Comment by jgnieuwhof** [comment]
@bdolly - interesting, wonder what's causing that. seems unrelated to this PR, we recently did merge some sidebare changes that may have introduced this. I'm ok with merging as-is and touching that up in a subsequent PR, but if you'd prefer to address now then that's cool too. there's a CSS refactor coming down the pike pretty soon, so it might also be reasonable to stash this issue & address it until after the refactor.

@hlminh2000, @bdolly  - thoughts?

**Comment by hlminh2000** [comment]
yeah if I'm ok with merging this as-is myself. We might find more problems with the image capture later, in which case it's still better to have it merged in master so we can continuously test I think.

**Comment by bdolly** [comment]
sounds good to me. That will give the team time to send in bugs and test the process as well

**Pull request merged**
