### PR TITLE
KF 2019-Q2-C

### PR DESCRIPTION
**Pull request by nyanofthemoon**

### CODE REVIEW

**Comment by nyanofthemoon** [comment]
@aalex Just need someone to review the PR.

**Comment by jberube** [comment]
@aalex I think that it suffice that the fields are present in ES and indexed (and the REACT_APP_PROJECT_ID environment variable is up to date).

**Comment by aalex** [comment]
Let's make sure to:
- Update the env var: REACT_APP_PROJECT_ID=2019_05_17_v3
- Merge, not squash
- Wait for the ETL to be ran before updating the UI.

**Comment by aalex** [comment]
> @aalex I think that it suffice that the fields are present in ES and indexed (and the REACT_APP_PROJECT_ID environment variable is up to date).

The problem is that we need the ETL to be ran, since the "Diagnosis (Mondo)" field that is live, right now, in prod, has its descriptions missing in its values.

**Comment by aalex** [comment]
I'll approve this PR when we have the OK from CHOP. No changes need to be done. Let's simply wait for the ETL to be ran on Thursday morning. The ETL needs about 3h to run, so by Thursday PM, we should be OK to deploy the UI with these changes included.

**Comment by nyanofthemoon** [comment]
@aalex I ran the ETL in Jenkins after speaking with CHOP. They mentioned that they do no QA on their end. What else do I need to do before I can deploy this release?

**Comment by nyanofthemoon** [comment]
@aalex I've changed the PRD environment variable vrom `may_2_2019_prd` to `2019_05_17_v3`.

**Pull request merged**
