### PR TITLE
User Integration Component, Save Cavatica Keys

### PR DESCRIPTION
**Pull request by joneubank**

### CODE REVIEW

**Comment by joneubank** [comment]
Needs styling help, especially on the Modal - need to integrate formatting provided by Minh in https://github.com/kids-first/kf-portal-ui/pull/98

**Comment by cy** [comment]
Could you rebase and delete this https://github.com/kids-first/kf-portal-ui/pull/99/files#diff-528c3923d718a8860f5d8c05c3931c55R40 line, I'd changed it to async load the lib after you pulled my branch, with `REACT_APP_GOOGLE_MAPS_KEY=` in .env

**Comment by joneubank** [comment]
Rebased and merged... messy commit history but working.

**Comment by joneubank** [comment]
Modal updated to use new modal state and components. Some styling of bulletted list needs updates, but looks much better than before.

**Comment by alex-wilmer** [comment]
hmm rebasing caused all of these commits to appear? how many of these commits are actually part of this PR? maybe it's worth rebasing again / or checking off master fresh and cherry picking them in. seems like the history got screwy somewhere along the way

**Comment by Jephuff** [comment]
re: using REACT_APP_GOOGLE_MAPS_KEY, you can use that in the index.html file. Just replace the key with `%REACT_APP_GOOGLE_MAPS_KEY%`

**Comment by joneubank** [comment]
Not sure how this branch became such a mess. I'm closing this and will open a shiny new one thats from the current master branch.

**Pull request closed without merging**
